name: "Ogrodje Site Build"
on:
  push:
    branches: [ master ]
  
  pull_request:
    branches: [ master ]

  repository_dispatch:
    branches: [ master ]

  workflow_dispatch:


env:
  HYGRAPH_ENDPOINT: ${{ secrets.HYGRAPH_ENDPOINT }}
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

jobs:
  build:
    name: Build
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  deploy:
    name: Deployment
    environment: ci
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/    
      - run: yarn install --frozen-lockfile
      - name: "Deploy"
        run: |
          netlify deploy \
            --site $NETLIFY_SITE_ID \
            --auth $NETLIFY_AUTH_TOKEN \
            --prod      
