name: "Ogrodje Site Build"
on:
  push:
    branches: [ master ]
  
  pull_request:
    branches: [ master ]

env:
  HYGRAPH_ENDPOINT: ${{ vars.HYGRAPH_ENDPOINT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "HE"
        echo $HYGRAPH_ENDPOINT
        echo ${{ vars.HYGRAPH_ENDPOINT }}

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: yarn install && yarn build
      
