name: "Ogrodje Site Build"
on:
  push:
    branches: [ master ]
  
  pull_request:
    branches: [ master ]

  repository_dispatch:
    branches: [ master ]

  workflow_dispatch:


env:
  HYGRAPH_ENDPOINT: ${{ secrets.HYGRAPH_ENDPOINT }}
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

jobs:
  build:
    name: "Build & Deploy"
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21 
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: "Deploy"
        run: |
          ./node_modules/.bin/netlify deploy \
            --site $NETLIFY_SITE_ID \
            --auth $NETLIFY_AUTH_TOKEN \
            --prod      
